# docker-compose.yml
services:
  fragments:
    image: yuelinwen/fragments-backend:latest
    init: true
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - AWS_REGION=us-east-1
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID
      - HTPASSWD
      - API_URL
      - AWS_S3_BUCKET_NAME=fragments-bucket
      - AWS_DYNAMODB_TABLE_NAME=fragments-table
