name: cd

on:
  push:
    tags:
      - 'v**'

jobs:
  aws:
    name: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials using Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: fragments-api
          VERSION_TAG: ${{ github.ref_name }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:${{ env.VERSION_TAG }}, ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO }}:latest

      # Elastic Beanstalk
      - name: Create compose file with specific Docker image info
        env:
          DOCKER_REPO: yuelinwen/fragments-backend
          DOCKER_TAG: latest
          COMPOSE_FILE: deploy-${{ github.ref_name }}.yml
        run: |
          envsubst < docker-compose.yml > ${{ env.COMPOSE_FILE }}
          echo "Created ${{ env.COMPOSE_FILE }}"

      # Deploy our custom compose file to our Elastic Beanstalk environment
      - name: Deploy to Elastic Beanstalk
        env:
          VERSION: ${{ github.ref_name }}
          COMPOSE_FILE: deploy-${{ github.ref_name }}.yml
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          # Make sure this matches your Elastic Beanstalk application name
          application_name: fragments-backend-api
          # Make sure this matches your Elastic Beanstalk environment name
          environment_name: Fragments-backend-api-env
          version_label: ${{ env.VERSION }}
          deployment_package: ${{ env.COMPOSE_FILE }}
